TABLE_KEYWORDS = {
    "Categories": [
        "category",
        "categories",
        "product category",
        "product type",
        "classification",
        "group",
        "family",
        "food type",
        "beverage",
        "condiment",
        "seafood",
        "dairy",
        "description",
        "picture"
    ],

    "Customers": [
        "customer",
        "customers",
        "client",
        "clients",
        "buyer",
        "buyers",
        "company",
        "company name",
        "contact",
        "contact name",
        "contact title",
        "address",
        "city",
        "region",
        "postal code",
        "country",
        "phone",
        "fax",
        "customer list",
        "customer location",
        "customer country"
    ],

    "Employees": [
        "employee",
        "employees",
        "staff",
        "worker",
        "sales representative",
        "salesperson",
        "manager",
        "reports to",
        "supervisor",
        "first name",
        "last name",
        "title",
        "birth date",
        "hire date",
        "address",
        "city",
        "region",
        "country",
        "home phone",
        "extension",
        "photo",
        "notes"
    ],

    "EmployeeTerritories": [
        "employee territory",
        "employee territories",
        "territory assignment",
        "employee area",
        "sales area",
        "employee region",
        "assigned territory",
        "territory by employee",
        "sales territory",
        "employee coverage"
    ],

    "Order Details": [
        "order details",
        "order lines",
        "order items",
        "line items",
        "products ordered",
        "ordered products",
        "quantity",
        "unit price",
        "discount",
        "sales amount",
        "order amount",
        "revenue",
        "total sales",
        "subtotal",
        "line total",
        "product sales",
        "items in order"
    ],

    "Orders": [
        "order",
        "orders",
        "customer order",
        "sales order",
        "purchase",
        "sales",
        "order date",
        "required date",
        "shipped date",
        "shipping",
        "ship via",
        "freight",
        "ship name",
        "ship address",
        "ship city",
        "ship region",
        "ship postal code",
        "ship country",
        "employee order",
        "customer purchases",
        "delivered orders",
        "pending orders"
    ],

    "Products": [
        "product",
        "products",
        "item",
        "items",
        "goods",
        "product name",
        "supplier product",
        "category product",
        "quantity per unit",
        "unit price",
        "units in stock",
        "stock",
        "inventory",
        "units on order",
        "reorder level",
        "discontinued",
        "available products",
        "out of stock",
        "expensive products",
        "cheap products"
    ],

    "Region": [
        "region",
        "regions",
        "sales region",
        "geographic region",
        "territory region",
        "area",
        "regional division",
        "region description"
    ],

    "Shippers": [
        "shipper",
        "shippers",
        "shipping company",
        "delivery company",
        "carrier",
        "freight company",
        "transport",
        "delivery",
        "ship via",
        "company name",
        "phone",
        "shipping method"
    ],

    "Suppliers": [
        "supplier",
        "suppliers",
        "vendor",
        "vendors",
        "provider",
        "product supplier",
        "company",
        "company name",
        "contact",
        "contact name",
        "contact title",
        "address",
        "city",
        "region",
        "postal code",
        "country",
        "phone",
        "fax",
        "homepage",
        "supplier location"
    ],

    "Territories": [
        "territory",
        "territories",
        "sales territory",
        "sales area",
        "area",
        "region territory",
        "territory description",
        "geographic area",
        "employee territory",
        "assigned area"
    ],

    "CustomerCustomerDemo": [
        "customer demographic",
        "customer demographics",
        "customer type",
        "customer segment",
        "customer category",
        "customer profile",
        "customer classification",
        "demographic assignment"
    ],

    "CustomerDemographics": [
        "customer demographic",
        "customer demographics",
        "customer type",
        "customer segment",
        "customer category",
        "customer profile",
        "demographic description",
        "customer classification"
    ]
}


def get_table_keywords(table_name: str) -> list[str]:
    return TABLE_KEYWORDS.get(table_name, [])